# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('date_time', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('object_number', models.IntegerField()),
                ('status', models.IntegerField()),
                ('handler', models.CharField(max_length=20)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
