# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
